name: PR
on: [pull_request]
jobs:
  pr:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/justin-yan/image/cicd-all:0.0.1
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: '0'

      - run: just cicd-pr
