name: Update packages
on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/justin-yan/image/cicd-all:0.0.1
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      with:
        fetch-depth: '2'
    - name: Update
      run: just update
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
      with:
        commit-message: Update packages version to match upstream
        title: 'Packages Update: ${{ steps.date.outputs.date }}'
        branch: 'update-${{ github.run_id }}'
